// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2v8dsPiJ0qXiJVedfi7wyODhiiSWipJU',
    appId: '1:199580243744:web:d64bf517e3b3994987e945',
    messagingSenderId: '199580243744',
    projectId: 'listify-to-do',
    authDomain: 'listify-to-do.firebaseapp.com',
    storageBucket: 'listify-to-do.appspot.com',
    measurementId: 'G-CV6QCHXH4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_91xyFwRsT5RuT1WvdA60aFIupJyt9o',
    appId: '1:199580243744:android:825130ac31abe4e287e945',
    messagingSenderId: '199580243744',
    projectId: 'listify-to-do',
    storageBucket: 'listify-to-do.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5c7g2-dTLa6QJefjxsfTmWq1cdwjlpsM',
    appId: '1:199580243744:ios:2aac4ae640a5428f87e945',
    messagingSenderId: '199580243744',
    projectId: 'listify-to-do',
    storageBucket: 'listify-to-do.appspot.com',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5c7g2-dTLa6QJefjxsfTmWq1cdwjlpsM',
    appId: '1:199580243744:ios:d1a77e8243c5dcc287e945',
    messagingSenderId: '199580243744',
    projectId: 'listify-to-do',
    storageBucket: 'listify-to-do.appspot.com',
    iosBundleId: 'com.example.listify.RunnerTests',
  );
}
